python main_evaluate.py campus_drive_sigOver_10ms_mini sigOver_1599 campus_drive_half_normal.npy campus_drive_sigOver_10ms_half_abnormal.npy 0.05

python main_evaluate.py campus_drive_sigOver_10ms_mini LOS-5M-USRP1_1599 campus_drive_half_normal.npy campus_drive_LOS-5M-USRP1_half_abnormal.npy 0.05

python main_evaluate.py campus_drive_sigOver_10ms_mini LOS-5M-USRP2_1599 campus_drive_half_normal.npy campus_drive_LOS-5M-USRP2_half_abnormal.npy 0.05

python main_evaluate.py campus_drive_sigOver_10ms_mini LOS-5M-USRP3_1599 campus_drive_half_normal.npy campus_drive_LOS-5M-USRP3_half_abnormal.npy 0.05

python main_evaluate.py campus_drive_sigOver_10ms_mini NLOS-5M-USRP1_1599 campus_drive_half_normal.npy campus_drive_NLOS-5M-USRP1_half_abnormal.npy 0.05

python main_evaluate.py campus_drive_sigOver_10ms_mini Dynamics-5M-USRP1_1599 campus_drive_half_normal.npy campus_drive_Dynamics-5M-USRP1_half_abnormal.npy0.05
