python main.py custom custom_lstm /net/adv_spectrum/SADlog/JCL /net/adv_spectrum/array_data --ratio_known_outlier 0.01 --ratio_pollution 0.1 --lr 0.0001 --n_epochs 60 --lr_milestone 50 --batch_size 128 --weight_decay 0.5e-6 --pretrain True --ae_lr 0.0001 --ae_n_epochs 60 --ae_batch_size 128 --ae_weight_decay 0.5e-3 --normal_class 0 --known_outlier_class 1 --n_known_outlier_classes 1 --seed 42 --normal_data_file ryerson_train_normal.npy --abnormal_data_file ryerson_ab_train_JCL_abnormal.npy --txt_result_file /net/adv_spectrum/SADlog/result_txt/full_results.txt

python main.py custom custom_lstm /net/adv_spectrum/SADlog/JCL_3199 /net/adv_spectrum/array_data --ratio_known_outlier 0.01 --ratio_pollution 0.1 --lr 0.0001 --n_epochs 60 --lr_milestone 50 --batch_size 128 --weight_decay 0.5e-6 --pretrain True --ae_lr 0.0001 --ae_n_epochs 60 --ae_batch_size 128 --ae_weight_decay 0.5e-3 --normal_class 0 --known_outlier_class 1 --n_known_outlier_classes 1 --seed 42 --normal_data_file ryerson_train_normal.npy --abnormal_data_file ryerson_ab_train_JCL_3199_abnormal.npy --txt_result_file /net/adv_spectrum/SADlog/result_txt/full_results.txt

python main.py custom custom_lstm /net/adv_spectrum/SADlog/JCL_1599 /net/adv_spectrum/array_data --ratio_known_outlier 0.01 --ratio_pollution 0.1 --lr 0.0001 --n_epochs 60 --lr_milestone 50 --batch_size 128 --weight_decay 0.5e-6 --pretrain True --ae_lr 0.0001 --ae_n_epochs 60 --ae_batch_size 128 --ae_weight_decay 0.5e-3 --normal_class 0 --known_outlier_class 1 --n_known_outlier_classes 1 --seed 42 --normal_data_file ryerson_train_normal.npy --abnormal_data_file ryerson_ab_train_JCL_1599_abnormal.npy --txt_result_file /net/adv_spectrum/SADlog/result_txt/full_results.txt

python main.py custom custom_lstm /net/adv_spectrum/SADlog/JCL_319 /net/adv_spectrum/array_data --ratio_known_outlier 0.01 --ratio_pollution 0.1 --lr 0.0001 --n_epochs 60 --lr_milestone 50 --batch_size 128 --weight_decay 0.5e-6 --pretrain True --ae_lr 0.0001 --ae_n_epochs 60 --ae_batch_size 128 --ae_weight_decay 0.5e-3 --normal_class 0 --known_outlier_class 1 --n_known_outlier_classes 1 --seed 42 --normal_data_file ryerson_train_normal.npy --abnormal_data_file ryerson_ab_train_JCL_319_abnormal.npy --txt_result_file /net/adv_spectrum/SADlog/result_txt/full_results.txt

python main.py custom custom_lstm /net/adv_spectrum/SADlog/downtown /net/adv_spectrum/array_data --ratio_known_outlier 0.01 --ratio_pollution 0.1 --lr 0.0001 --n_epochs 60 --lr_milestone 50 --batch_size 128 --weight_decay 0.5e-6 --pretrain True --ae_lr 0.0001 --ae_n_epochs 60 --ae_batch_size 128 --ae_weight_decay 0.5e-3 --normal_class 0 --known_outlier_class 1 --n_known_outlier_classes 1 --seed 42 --normal_data_file ryerson_train_normal.npy --abnormal_data_file ryerson_ab_train_downtown_abnormal.npy --txt_result_file /net/adv_spectrum/SADlog/result_txt/full_results.txt

python main.py custom custom_lstm /net/adv_spectrum/SADlog/downtown_3199 /net/adv_spectrum/array_data --ratio_known_outlier 0.01 --ratio_pollution 0.1 --lr 0.0001 --n_epochs 60 --lr_milestone 50 --batch_size 128 --weight_decay 0.5e-6 --pretrain True --ae_lr 0.0001 --ae_n_epochs 60 --ae_batch_size 128 --ae_weight_decay 0.5e-3 --normal_class 0 --known_outlier_class 1 --n_known_outlier_classes 1 --seed 42 --normal_data_file ryerson_train_normal.npy --abnormal_data_file ryerson_ab_train_downtown_3199_abnormal.npy --txt_result_file /net/adv_spectrum/SADlog/result_txt/full_results.txt

python main.py custom custom_lstm /net/adv_spectrum/SADlog/downtown_1599 /net/adv_spectrum/array_data --ratio_known_outlier 0.01 --ratio_pollution 0.1 --lr 0.0001 --n_epochs 60 --lr_milestone 50 --batch_size 128 --weight_decay 0.5e-6 --pretrain True --ae_lr 0.0001 --ae_n_epochs 60 --ae_batch_size 128 --ae_weight_decay 0.5e-3 --normal_class 0 --known_outlier_class 1 --n_known_outlier_classes 1 --seed 42 --normal_data_file ryerson_train_normal.npy --abnormal_data_file ryerson_ab_train_downtown_1599_abnormal.npy --txt_result_file /net/adv_spectrum/SADlog/result_txt/full_results.txt

python main.py custom custom_lstm /net/adv_spectrum/SADlog/downtown_319 /net/adv_spectrum/array_data --ratio_known_outlier 0.01 --ratio_pollution 0.1 --lr 0.0001 --n_epochs 60 --lr_milestone 50 --batch_size 128 --weight_decay 0.5e-6 --pretrain True --ae_lr 0.0001 --ae_n_epochs 60 --ae_batch_size 128 --ae_weight_decay 0.5e-3 --normal_class 0 --known_outlier_class 1 --n_known_outlier_classes 1 --seed 42 --normal_data_file ryerson_train_normal.npy --abnormal_data_file ryerson_ab_train_downtown_319_abnormal.npy --txt_result_file /net/adv_spectrum/SADlog/result_txt/full_results.txt

python main.py custom custom_lstm /net/adv_spectrum/SADlog/ryerson_t2 /net/adv_spectrum/array_data --ratio_known_outlier 0.01 --ratio_pollution 0.1 --lr 0.0001 --n_epochs 60 --lr_milestone 50 --batch_size 128 --weight_decay 0.5e-6 --pretrain True --ae_lr 0.0001 --ae_n_epochs 60 --ae_batch_size 128 --ae_weight_decay 0.5e-3 --normal_class 0 --known_outlier_class 1 --n_known_outlier_classes 1 --seed 42 --normal_data_file ryerson_train_normal.npy --abnormal_data_file ryerson_ab_train_ryerson_t2_abnormal.npy --txt_result_file /net/adv_spectrum/SADlog/result_txt/full_results.txt

python main.py custom custom_lstm /net/adv_spectrum/SADlog/ryerson_t2_3199 /net/adv_spectrum/array_data --ratio_known_outlier 0.01 --ratio_pollution 0.1 --lr 0.0001 --n_epochs 60 --lr_milestone 50 --batch_size 128 --weight_decay 0.5e-6 --pretrain True --ae_lr 0.0001 --ae_n_epochs 60 --ae_batch_size 128 --ae_weight_decay 0.5e-3 --normal_class 0 --known_outlier_class 1 --n_known_outlier_classes 1 --seed 42 --normal_data_file ryerson_train_normal.npy --abnormal_data_file ryerson_ab_train_ryerson_t2_3199_abnormal.npy --txt_result_file /net/adv_spectrum/SADlog/result_txt/full_results.txt

python main.py custom custom_lstm /net/adv_spectrum/SADlog/ryerson_t2_1599 /net/adv_spectrum/array_data --ratio_known_outlier 0.01 --ratio_pollution 0.1 --lr 0.0001 --n_epochs 60 --lr_milestone 50 --batch_size 128 --weight_decay 0.5e-6 --pretrain True --ae_lr 0.0001 --ae_n_epochs 60 --ae_batch_size 128 --ae_weight_decay 0.5e-3 --normal_class 0 --known_outlier_class 1 --n_known_outlier_classes 1 --seed 42 --normal_data_file ryerson_train_normal.npy --abnormal_data_file ryerson_ab_train_ryerson_t2_1599_abnormal.npy --txt_result_file /net/adv_spectrum/SADlog/result_txt/full_results.txt

python main.py custom custom_lstm /net/adv_spectrum/SADlog/ryerson_t2_319 /net/adv_spectrum/array_data --ratio_known_outlier 0.01 --ratio_pollution 0.1 --lr 0.0001 --n_epochs 60 --lr_milestone 50 --batch_size 128 --weight_decay 0.5e-6 --pretrain True --ae_lr 0.0001 --ae_n_epochs 60 --ae_batch_size 128 --ae_weight_decay 0.5e-3 --normal_class 0 --known_outlier_class 1 --n_known_outlier_classes 1 --seed 42 --normal_data_file ryerson_train_normal.npy --abnormal_data_file ryerson_ab_train_ryerson_t2_319_abnormal.npy --txt_result_file /net/adv_spectrum/SADlog/result_txt/full_results.txt

python main.py custom custom_lstm /net/adv_spectrum/SADlog/searle /net/adv_spectrum/array_data --ratio_known_outlier 0.01 --ratio_pollution 0.1 --lr 0.0001 --n_epochs 60 --lr_milestone 50 --batch_size 128 --weight_decay 0.5e-6 --pretrain True --ae_lr 0.0001 --ae_n_epochs 60 --ae_batch_size 128 --ae_weight_decay 0.5e-3 --normal_class 0 --known_outlier_class 1 --n_known_outlier_classes 1 --seed 42 --normal_data_file ryerson_train_normal.npy --abnormal_data_file ryerson_ab_train_searle_abnormal.npy --txt_result_file /net/adv_spectrum/SADlog/result_txt/full_results.txt

python main.py custom custom_lstm /net/adv_spectrum/SADlog/searle_3199 /net/adv_spectrum/array_data --ratio_known_outlier 0.01 --ratio_pollution 0.1 --lr 0.0001 --n_epochs 60 --lr_milestone 50 --batch_size 128 --weight_decay 0.5e-6 --pretrain True --ae_lr 0.0001 --ae_n_epochs 60 --ae_batch_size 128 --ae_weight_decay 0.5e-3 --normal_class 0 --known_outlier_class 1 --n_known_outlier_classes 1 --seed 42 --normal_data_file ryerson_train_normal.npy --abnormal_data_file ryerson_ab_train_searle_3199_abnormal.npy --txt_result_file /net/adv_spectrum/SADlog/result_txt/full_results.txt

python main.py custom custom_lstm /net/adv_spectrum/SADlog/searle_1599 /net/adv_spectrum/array_data --ratio_known_outlier 0.01 --ratio_pollution 0.1 --lr 0.0001 --n_epochs 60 --lr_milestone 50 --batch_size 128 --weight_decay 0.5e-6 --pretrain True --ae_lr 0.0001 --ae_n_epochs 60 --ae_batch_size 128 --ae_weight_decay 0.5e-3 --normal_class 0 --known_outlier_class 1 --n_known_outlier_classes 1 --seed 42 --normal_data_file ryerson_train_normal.npy --abnormal_data_file ryerson_ab_train_searle_1599_abnormal.npy --txt_result_file /net/adv_spectrum/SADlog/result_txt/full_results.txt

python main.py custom custom_lstm /net/adv_spectrum/SADlog/searle_319_new /net/adv_spectrum/array_data --ratio_known_outlier 0.01 --ratio_pollution 0.1 --lr 0.0001 --n_epochs 60 --lr_milestone 50 --batch_size 128 --weight_decay 0.5e-6 --pretrain True --ae_lr 0.0001 --ae_n_epochs 60 --ae_batch_size 128 --ae_weight_decay 0.5e-3 --normal_class 0 --known_outlier_class 1 --n_known_outlier_classes 1 --seed 42 --normal_data_file ryerson_train_normal.npy --abnormal_data_file ryerson_ab_train_searle_319_abnormal.npy --txt_result_file /net/adv_spectrum/SADlog/result_txt/full_results.txt
